### ISSUE TITLE
Pb d'installation

### ISSUE THREAD

**Issue by diatodan** [oliviervalentin/moodle-report_coursemanager#2]
Bonjour Olivier,

Merci beaucoup pour la présentation au Moodle Moot, c'était top !!
J'ai effectivement rencontré un bug à l'installation de la version V2 :

[Erreur] Le plugin ne déclare pas sa version [null]

Voici ma version de Moodle : Moodle 4.1.4+

**Comment by oliviervalentin** [comment]
Merci pour ce retour !! :)
Je vais chercher l'origine du problème.
Sur le coup, c'est très bizarre. Ma version est pourtant bien déclarée dans le fichier version.php qui est à a racine du plugin. 
Je vais m’installer une version identique et je ferai un retour aussi vite que possible.
Olivier

**Comment by oliviervalentin** [comment]
Re,
j'ai installé à l'instant un package Moodle en 4.1.4+ ((Build: 20230629) et tenté d'installer Course Manager... sans rencontrer de problème. :(
S'il existe des captures d'écrans précises, je suis preneur !
Et si possible, vérifier sur le serveur que le fichier version.php se trouve bien à la racine. Si le message se reporte bien à un problème de version, je ne vois pas d'autre endroit d'où pourrait provenir le souci.
Tenez-moi au courant ! 
Olivier

**Comment by diatodan** [comment]
Le fichier version.php est bien présent.
J'ai pensé à un problème de permissions sur ce fichier mais ça ne semble pas être ça.
La V1 s'installe sans difficultés.
Peu de connexion dans le train mais je vais creuser aussi de mon côté !

Daniel

<img width="529" alt="SCR-20230707-lcso" src="https://github.com/oliviervalentin/moodle-report_coursemanager/assets/7548834/4bc7730c-c323-4972-a838-4dbb1109a074">

**Comment by oliviervalentin** [comment]
Je crois que je tiens une piste....
Je vois dans ta capture que tu as téléchargé le zip pour le charger dans la zone de dépôt du zip d'installation des plugins. Or dans GitHub, quand je télécharge le zip, le dossier qu'il contient porte un nom à rallonge. Or, dans mes souvenirs, il est censé juste s'appeler "coursemanager" ! Je parierais presque que ça vient de là !
Si tu as la possibilité, télécharge le zip, extrais le dossier du plugin, renomme-le simplement "coursemanager" et uploade-le par FTP dans le dossier "report" à la racine de Moodle, et lance l'installation.

Olivier

**Comment by oliviervalentin** [comment]
EDIT : gagné... :)
![image](https://github.com/oliviervalentin/moodle-report_coursemanager/assets/25584834/c728dd54-67e0-4a91-b66c-29d64b203012)

Mais même en nommant le dossier "coursemanager" à l'intérieur du zip, je n'arrive pas à installer. Mais au moins, je reproduis le bug !

Olivier

**Comment by diatodan** [comment]
Olivier,
J'ai réussi à l'installer de mon côté en nommant le dossier "coursemanager" et en copiant les fichiers directement en FTP dans le dossier "report".
Je crois que tu as échangé avec Vincent concernant la possibilité d'avoir une vue "admin", je suis intéressé d'explorer cette fonctionnalité !

**Comment by oliviervalentin** [comment]
Daniel,
je pense que le problème est résolu ! Je me rends compte qu'il y avait des quotes autour du numéros de versions du plugin et de la version Moodle nécessaire à l'installation. Je viens de les retirer, et le problème semble avoir disparu. Comme d'habitude, une ponctuation et tout part en sucette ! :)
Si tu as le temps de tester de ton côté, mais en tout cas, ça fonctionne parfaitement de mon coté.
Olivier

**Comment by diatodan** [comment]
Olivier,
Je te confirme que l'installation à partir du ZIP est bien fonctionnelle.
Je vais reprendre contact avec toi par email concernant ma question sur la vue admin.
Merci beaucoup !
Daniel

**Comment by oliviervalentin** [comment]
Daniel,
merci pour cette confirmation ! Je clos le ticket.
Je suis en train de réfléchir à la façon d'organiser la réflexion, peut-être avec un Monday ou un Freedcamp. Si tu as des pistes...
Olivier
