### ISSUE TITLE
Mauvais lien pour ajouter des cohortes

### ISSUE THREAD

**Issue by gmanaud** [oliviervalentin/moodle-report_coursemanager#3]
Bonjour,

Merci pour ce plugin très intéressant et la présentation au MoodleMoot !

Sur notre Moodle, le lien pour ajouter des cohortes menait vers une page d'erreur (répertoire /enrol/scolarite n'existe pas chez nous, plugin local ?). De notre côté, nous utilisons la méthode de synchronisation des cohortes.

Dans le fichier `view.php`, j'ai modifié la ligne 
`<a class="dropdown-item" href="/enrol/scolarite/manage.php?id='.$course->id.'">Ajouter des cohortes</a>`
par
`<a class="dropdown-item" href="/enrol/editinstance.php?type=cohort&courseid='.$course->id.'">Ajouter des cohortes</a>`

Cela permet d'accéder directement à la page d'ajout d'une cohorte avec cette méthode d'inscription.

Par contre je ne sais pas si ce sera adapté pour tout le monde.

**Comment by oliviervalentin** [comment]
Bonjour,
c'est en effet le cas : il s'agit d'un outil spécifique à Lyon 3. Notre méthode d'inscription, qui s'appelle Scolarité, est la méthode privilégiée des enseignants pour inscrire des cohortes.
Je me demande s'il ne serait pas pertinent de trouver le moyen de définir la méthode d'inscription privilégiée dans l'administration du plugin et/ou de l'activer dans l'interface.
Je suis en train de réfléchir à comment organiser la réflexion, les votes, les priorités etc. du projet.
Olivier

**Comment by oliviervalentin** [comment]
Résolu : le plugin étudie si la méthode d'inscription Scolarité, propre à Lyon 3, est activée ou pas. Si non, le lien disparait simplement du menu.
