### ISSUE TITLE
styles.css not specific enough.

### ISSUE THREAD

**Issue by danmarsden** [oliviervalentin/moodle-report_coursemanager#32]
string concatentaion in the lang packs is not allowed - it causes problems for the Moodle translation tool

eg:
$string['test'] = "sometext"."somemoretext";
or
$string['test'] = "sometext".$string['someotheritem'];

each string must be contained within one set of quotes eg:
$string['test'] = "sometext somemoretext";

**Comment by oliviervalentin** [comment]
Hi @danmarsden ,
seems there's a problem with this issue, for the title doesn't fit with text... and the same text is in another issue you've brought about strings concatenation ! :)
Is there a problem with CSS coding style ?
Best regards,
Olivier

**Comment by danmarsden** [comment]
haha - whoops - failure there on my canned responses - sorry about that!!! - correct text for that is....


in your styles.css you define a number of generic styles that could clash with core moodle code or other locations where simliar names are used. 

Moodle helpfully adds a number of classes to the body tag based on the path that you can use such as:
eg if you are have a file in mod/assign you would see the following class added to the body tag
path-mod-assign
so if you have an item with the class "filething" on the page you would target it like:
```
.path-mod-assign .filething {
   color: red;
}
```

Please make sure your css classes in styles.css are specific enough so they cannot clash with other core code.

**Comment by oliviervalentin** [comment]
Add class for pages and changed styles.css.
