### ISSUE TITLE
missing sesskey checks in custom form / action pages like delete_course/delete_cohort

### ISSUE THREAD

**Issue by danmarsden** [oliviervalentin/moodle-report_coursemanager#34]
take a look at the docs here that show what you should be doing in there:
https://moodledev.io/general/development/policies/security/crosssite-request-forgery#what-you-need-to-do-in-your-code

**Comment by oliviervalentin** [comment]
Add sesskey check for delete_cohort, delete_course, orphaned_submissions, courses_without_teachers and restore_course.
Watch in future if all action are well sesskey checked.
