### ISSUE TITLE
incorrect class name (and in wrong place)

### ISSUE THREAD

**Issue by danmarsden** [oliviervalentin/moodle-report_coursemanager#35]
https://github.com/oliviervalentin/moodle-report_coursemanager/blob/main/lib.php#L275

that class should ideally sit in it's own file and must follow our frankenstyle naming conventions or be namespaced.

more info on this is here:
https://moodledev.io/general/development/policies/codingstyle/frankenstyle#class-names

note this is a blocker for plugins db approval.

**Comment by oliviervalentin** [comment]
Class renamed and isolated in separated file if necessary.
