### ISSUE TITLE
hard coded roleid?

### ISSUE THREAD

**Issue by danmarsden** [oliviervalentin/moodle-report_coursemanager#36]
https://github.com/oliviervalentin/moodle-report_coursemanager/blob/main/lib.php#L328C1-L328C36

What's that code doing? - why are you doing a roleid > 2 there? - typically usage of hard-coded roleid's is a blocker for plugins db approval.

**Comment by oliviervalentin** [comment]
Hi Dan,
when a course contains reports, they can be displayed in a course. But initially, only teachers were concerned. After some discussions, I thought it was a good thing that some higher admins could have a view too on reports in course, i.e. admin and course creator. As they can see all courses, those reports information could be useful for them.

Re-reading my code, why haven't I implemented a permissions instead ?? Awful error, I will correct this in future...

Olivier

**Comment by oliviervalentin** [comment]
Add capability file and changed code for checking teachers role (as defined in settings) or capability for admins.
