### ISSUE TITLE
String concatenation is not allowed in lang files

### ISSUE THREAD

**Issue by danmarsden** [oliviervalentin/moodle-report_coursemanager#38]
https://github.com/oliviervalentin/moodle-report_coursemanager/blob/main/lang/fr/report_coursemanager.php#L123

I couldn't see any in the english language pack but could see some in the french one.

string concatentaion in the lang packs is not allowed - it causes problems for the Moodle translation tool

eg:
$string['test'] = "sometext"."somemoretext";
or
$string['test'] = "sometext".$string['someotheritem'];

each string must be contained within one set of quotes eg:
$string['test'] = "sometext somemoretext";

**Comment by oliviervalentin** [comment]
Concatenations deleted in french translation.
