### ISSUE TITLE
missing capability checks in admin_dashboard files

### ISSUE THREAD

**Issue by danmarsden** [oliviervalentin/moodle-report_coursemanager#39]
the admin_dashboard files seem to allow moving of courses, deleting of data but no capability checks are performed to check "is this user allowed to do this"

please see:
https://moodledev.io/general/development/policies/security#verify-course-and-module-access

note this is a blocker for plugins db approval

**Comment by oliviervalentin** [comment]
Hi Dan,
well noted. This will be implemented in next version.
Best regards,
Olivier

**Comment by oliviervalentin** [comment]
Add capability for admin tools.
