### ISSUE TITLE
take a look at get_in_or_equal

### ISSUE THREAD

**Issue by danmarsden** [oliviervalentin/moodle-report_coursemanager#42]
This:
https://github.com/oliviervalentin/moodle-report_coursemanager/blob/main/admin_dashboard/courses_without_teachers.php#L143

should really be using the get_in_or_equal helper so that the values get passed as parameters correctly - (with a fallback to a simple = if there is only one value/one admin returned.)

more info on this is here:
https://moodledev.io/docs/apis/core/dml#get_in_or_equal

**Comment by oliviervalentin** [comment]
OK fixed... 
This function is not very easy to use, huge thanks to @cybercells for helping ! :)
