### ISSUE TITLE
invalid table name "coursemanager"

### ISSUE THREAD

**Issue by danmarsden** [oliviervalentin/moodle-report_coursemanager#43]
Tables must use the frankenstyle naming convention as per:
https://moodledev.io/general/development/policies/codingstyle/frankenstyle#table-names

all your tables need to be named with the prefix "report_coursemanager" - not "coursemanager" on it's own.

so valid table names are like: report_coursemanager, report_coursemanager_user, report_coursemanager_thing etc

this one is a blocker for plugins db approval.

**Comment by oliviervalentin** [comment]
OK fixed, table rename to "report_coursemanager_reports".
Name changed in codes and add update function to rename table.
