### ISSUE TITLE
weird config.php file?

### ISSUE THREAD

**Issue by danmarsden** [oliviervalentin/moodle-report_coursemanager#44]
the config.php file looks like it's got something that looks like a $THEME array and looks like it might have accidentally been copied from a theme? - can it be deleted?

https://github.com/oliviervalentin/moodle-report_coursemanager/blob/main/config.php

**Comment by oliviervalentin** [comment]
Totally useles... deleted !
I had forgotten this file : initially, Course Manager was thought as an extension for my template, before I decided to code it as a report.
