### ISSUE TITLE
weird theme_navcoursemanager_extend_navigation function in lib.php

### ISSUE THREAD

**Issue by danmarsden** [oliviervalentin/moodle-report_coursemanager#45]
looks like a left-over from a previous theme? - it's probably not doing anything and could be deleted.

it needs to be deleted or renamed as it violates the frankenstyle naming conventions for functions anyway...

**Comment by oliviervalentin** [comment]
Useless too !
As for config.php, this code was a test to add a navigation node when Course Manager was built as a theme plugin.
Code deleted !
