### ISSUE TITLE
styles.css not specific enough

### ISSUE THREAD

**Issue by danmarsden** [oliviervalentin/moodle-report_coursemanager#47]
in your styles.css you define a number of generic styles that could clash with core moodle code or other locations where simliar names are used. 

Moodle helpfully adds a number of classes to the body tag based on the path that you can use such as:
eg if you are have a file in mod/assign you would see the following class added to the body tag
path-mod-assign
so if you have an item with the class "filething" on the page you would target it like:
```
.path-mod-assign .filething {
   color: red;
}
```

Please make sure your css classes in styles.css are specific enough so they cannot clash with other core code. 

one example from your code:
https://github.com/oliviervalentin/moodle-report_coursemanager/blob/main/styles.css#L54

I see you're trying to show that button within a normal course page, so you can't target it with something like .path-report-coursemanager so you probably want to rename the class itself and make it "report-cousremanager-reportbutton"

that way if someone else in Moodle uses "reportbutton" on it's own it won't clash with your css.

**Comment by oliviervalentin** [comment]
OK, add more specifics name when needed. Hope all styles are fine now !

**Comment by danmarsden** [comment]
it's definitely better than it was...

it would still be nice to clean up some of the rules in this block:
https://github.com/oliviervalentin/moodle-report_coursemanager/blob/main/styles.css#L19-L34

as that might hit other code and not just reports from your plugin.

**Comment by oliviervalentin** [comment]
Damn, I have forgotten these styles...
Hope it's fixed now.
