### ISSUE TITLE
orphaned submissions db error when using postgres

### ISSUE THREAD

**Issue by danmarsden** [oliviervalentin/moodle-report_coursemanager#49]
Debug info: ERROR: column "f.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ....filesize) AS filesize, u.id , u.firstname, u.lastname, f.id
^
SELECT DISTINCT(f.filesize) AS filesize, u.id , u.firstname, u.lastname, f.id
FROM
mdl_files AS f,
mdl_assignsubmission_file AS asf,
mdl_assign AS a,
mdl_user AS u,
mdl_course AS c,
mdl_course_modules AS cm
WHERE
component = 'assignsubmission_file'
AND asf.submission=f.itemid
AND a.id = asf.assignment
AND f.userid = u.id
AND filename != '.'
AND c.id = a.course
AND a.id = $1
AND a.id = cm.instance
AND u.id NOT IN
(SELECT us.id
FROM
mdl_course AS course,
mdl_enrol AS en,
mdl_user_enrolments AS ue,
mdl_user AS us
WHERE c.id=course.id
AND en.courseid = course.id
AND ue.enrolid = en.id
AND us.id = ue.userid
)
GROUP BY filesize, u.id

[array (
0 => '5',
)]
Error code: dmlreadexception

**Comment by oliviervalentin** [comment]
New version pushed, hoping it will solve this problem.

**Comment by danmarsden** [comment]
I don't get that error on my testing site anymore (but I have no orphaned files) - probably fine to close this one.
