### ISSUE TITLE
teacher dashboard (view.php) search doesn't work

### ISSUE THREAD

**Issue by danmarsden** [oliviervalentin/moodle-report_coursemanager#51]
I'm testing on Moodle 4.4dev so not sure what versions this works in, but if I put text into the search bar I see JS errors in my console like:
view.php:426 Uncaught ReferenceError: myFunction is not defined
    at HTMLInputElement.onkeyup (view.php:426:112)

and the search doesn't seem to do anything.

I do only have 2 courses in this site I'm testing with so not sure if that makes a difference too.

**Comment by oliviervalentin** [comment]
Fixed : the JS file for this function was deleted ! It's back... :)
