### ISSUE TITLE
error when no heavy courses found.

### ISSUE THREAD

**Issue by danmarsden** [oliviervalentin/moodle-report_coursemanager#53]
when viewing the course manager for teachers report, I get the following error:

Debug info: SELECT * FROM {course} WHERE id IS NULL
[array (
)]
Error code: invalidrecord×Dismiss this notification
Stack trace:
line 1659 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
line 1635 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
line 628 of /lib/datalib.php: call to moodle_database->get_record()
line 92 of /report/coursemanager/admin_dashboard/stats.php: call to get_course()

I only have a couple of courses in my testing instance and running the scheduled tasks didn't seem to clear the error.

**Comment by oliviervalentin** [comment]
OK, I think this happens when no reports are found for this aspect.
I fixed this page, should work now...

**Comment by danmarsden** [comment]
yeah that did it - if you upload the latest version to the plugins db entry as well I think this might be ready to go! :-)

**Comment by oliviervalentin** [comment]
OK I close this one.
