### ISSUE TITLE
Manage courses without teachers - Error reading from database

### ISSUE THREAD

**Issue by caiadogithub** [oliviervalentin/moodle-report_coursemanager#54]
Moodle 4.1
PostgreSQL 16
PHP 7.4
Ubuntu 

----------------

/report/coursemanager/admin_dashboard/courses_without_teachers.php#

Debug info: ERRO: coluna "useridnot" não existe
LINE 7: AND useridNOT IN ($2,$3))
^
HINT: Talvez você queira fazer referência à coluna "mdl_logstore_standard_log.userid" ou à coluna "mdl_logstore_standard_log.userid".
SELECT id, userid AS teacher, timecreated AS lastlog
FROM mdl_logstore_standard_log
WHERE timecreated = (SELECT MAX(timecreated)
FROM mdl_logstore_standard_log
WHERE courseid = $1
AND edulevel = 1
AND useridNOT IN ($2,$3))
[array (
0 => '22621',
1 => 2,
2 => 3,
)]
Error code: dmlreadexception Stack trace:

    line 494 of /lib/dml/moodle_database.php: dml_read_exception thrown
    line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
    line 341 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->read_slave_query_end()
    line 1027 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
    line 1679 of /lib/dml/moodle_database.php: call to pgsql_native_moodle_database->get_records_sql()
    line 154 of /report/coursemanager/admin_dashboard/courses_without_teachers.php: call to moodle_database->get_record_sql()

**Comment by oliviervalentin** [comment]
Possible ! In my code, I used the "get_in_or_equal" tool, it seems there is a space missing when userid concatenates ID lists.
I will push it very soon, after I correct some other bugs.
Thank you @caiadogithub  for your message ! :)
Olivier

**Comment by oliviervalentin** [comment]
Fixed - New version released
