### ISSUE TITLE
Files distribution by component - 

### ISSUE THREAD

**Issue by caiadogithub** [oliviervalentin/moodle-report_coursemanager#55]
Moodle 4.1
PostgreSQL 16
PHP 7.4
Ubuntu

-----------------------

/report/coursemanager/admin_dashboard/files_distribution.php

Did you remember to make the first column something unique in your call to get_records? Duplicate value '2' found in column 'totalfiles'.

    line 1049 of /lib/dml/pgsql_native_moodle_database.php: call to debugging()
    line 65 of /report/coursemanager/admin_dashboard/files_distribution.php: call to pgsql_native_moodle_database->get_records_sql()

**Comment by oliviervalentin** [comment]
Hi @caiadogithub !
Thank you again for this message !
OK, I saw this error. I user get_record_sql for my query, but I should use get_recordset_sql. Using this solves this problem.
I push this modification as soon as possible !
Olivier

**Comment by oliviervalentin** [comment]
Fixed - new version released.
