### ISSUE TITLE
Admin dashboard – Orphaned submissions report

### ISSUE THREAD

**Issue by gmanaud** [oliviervalentin/moodle-report_coursemanager#57]
Hello,

I can't view the orphaned files report on the Admin dashboard. The request seems too long to load and the page loads indefinitely for hours without displaying anything (this is probably a bad sign :D).

Is this a known problem and is there a solution?

Course Manager version 3.1.1
Moodle version 4.1

**Comment by oliviervalentin** [comment]
Hello,
maybe linked with you issue #58 : seems the report for orphaned submissions has problems to be calculated on your instance.
Are there any messages in debug mode or in task logs ?
Do you use MariaDB or PostGreS ?
Olivier

**Comment by gmanaud** [comment]
I use MariaDB.
No message in debug mode, page is just loading.
I just have a PHP notice in httpd logs:
Error: Cannot obtain session lock for sid: qqaufv3l1f50260d4j24suj8aj within 120 seconds. It is likely another page ([pid 150257] moodlename:/report/coursemanager/admin_dashboard/orphaned_submissions.php) has a long session lock, or the session lock was never released., referer: https:/moodleaddress/admin/search.php
