### ISSUE TITLE
Reports tasks very long

### ISSUE THREAD

**Issue by gmanaud** [oliviervalentin/moodle-report_coursemanager#58]
Hello,

Since version 3.1.1 (I was previously on version 2), reporting tasks for courses take a very long time to run. Their execution lasts more than a day, compared to 5 to 40 minutes previously.

However, I don't see any major change in the task. Where could this come from?

**Comment by oliviervalentin** [comment]
Hello,

could it be the orphaned submissions calculation that takes a too long time ? That's the main element that has been brought in task.

When task calculates reports for each course, a request first detects if there are assigns in course. If there are some, then report for searching orphaned submissions and their weights is triggered.

Just for a comparison, how many courses does your platform counts ?
Are there any reports for orphaned submissions calculated ?

Olivier

**Comment by gmanaud** [comment]
> could it be the orphaned submissions calculation that takes a too long time ? That's the main element that has been brought in task.
Probably! We have approximately 5 000 courses, and some of them were created in 2012.
I saw that a lot of courses actually contained orphaned files.

**Comment by oliviervalentin** [comment]
I relaunch it on my prod instance to see how many time it takes.
I tested it on test instance and fully worked. But it seems that orphaned submissions calculation is too long... Maybe I should put it as optionnal and seperate it in another task running only each week... 

I start to work on this right now and will push a new version very soon.

**Comment by oliviervalentin** [comment]
It took a very long time to set all reports because of the orphaned submissions calculation.
I'm working on a way to reduce this. I will certainly put it as an optionnal feature. 
Thanks for reporting this.

**Comment by gmanaud** [comment]
Thanks, it's just perfect!
Do you think it would be possible to use this report to display the orphaned submissions in the admin dashboard?

**Comment by oliviervalentin** [comment]
Yes : that's my next step ! :D

Now that it perfectly works, I first want to extend this work by separating each kind of reports in a distinct task. it will be more efficient, and admin will now be able to select the reports he wants to calculate or note. It is almost finished, it was just about isolating my code and creating a new task for each. I will then test it with a time reference to compare it to the initial task that calculates all reports at once.

As soon as it is finished (probably next week), I will then recode the orphaned submissions dashboard, to be based on the new table, and will try to offer a more efficient interface (filtering, navigation between pages...)

For now, I keep this issue opened and will close it when it is done.

Stay tuned ! :)

**Comment by oliviervalentin** [comment]
New release v3.2.1-stable released that fixes orphaned submissions problem.
See release notes to take aknowledgments of all improvments.
Let me now if this solves problem !

Olivier

**Comment by gmanaud** [comment]
It works perfectly now, thanks!
