### ISSUE TITLE
Paramétrer le rôle qui peut voir la liste des cours

### ISSUE THREAD

**Issue by oliviervalentin** [oliviervalentin/moodle-report_coursemanager#6]
Actuellement, la personne qui consulter le tableau verra tous les cours dans lequel il est enseignant. Or, certains Moodle ont des rôles personnalisés ou différents. Il peut être intéressant de pouvoir choisir le rôle qui aura le droit de voir la liste.

Doit-on choisir un seul rôle, ou plusieurs ?

Est-ce que ce choix peut rentrer en conflit avec les droits accordés ?

**Comment by gmanaud** [comment]
Est-ce qu'on ne ferait pas passer un paramètre dans les paramètres globaux du plugin pour que chaque administrateur puisse définir :
– les rôles qui peuvent voir la liste des cours
– les rôles qui seront sollicités lors de la suppression d'un cours (par mail et listés sur la page delete_course.php)
– les rôles qui seront comptés pour donner le nombre d'enseignants inscrits dans le cours ?

Dans mon cas ce ne sont pas les mêmes rôles qui peuvent voir la liste des cours et qui sont avertis de la suppression.

**Comment by oliviervalentin** [comment]
Tout à fait ! 
Typiquement, c'est la preuve que le plugin est actuellement adapté à un fonctionnement plutôt "natif" de Moodle, mais qu'il ne tient pas compte des autres rôles que pourraient utiliser d'autres plateformes. La sélection des rôles (même pour le calcul des étudiants !) est importante.

**Comment by oliviervalentin** [comment]
OK fait.
