### ISSUE TITLE
Courses not deleted in report_coursemanager_reports

### ISSUE THREAD

**Issue by gmanaud** [oliviervalentin/moodle-report_coursemanager#60]
Hi (again ! ;) )

A course deleted manually (without using coursemanager and without being in trash category) isn't deleted in the report_coursemanager_reports table. This causes errors (« Can not find data record in database table course ») when trying to display courses without teacher in admin dashboard.

Maybe it would be necessary to test if course exists and if no, delete the record?

**Comment by oliviervalentin** [comment]
Hi (once again !! :D),

totally logical... I'll do this for courses without teachers page. Orphaned submissions page could also be impacted. I'll fix that as soon as possible.
I must admit I didn't thought about this case. Maybe more to discover... :/
Olivier

**Comment by gmanaud** [comment]
Yes indeed, or maybe in a separate task that would be launched only if at least one report is enabled in the plugin settings?

**Comment by oliviervalentin** [comment]
I should add your name in co-credits for this plugin... :)

**Comment by oliviervalentin** [comment]
I have updated "courses without teachers" admin page.
- If weight report has not been calculated and report is enabled, a message will warn that some courses may not appear if their weights have not been calculated.
- Code now first checks if course exists in database. If not, course is not concerned. 

The reports cleaning will be added as a task soon.
